In [1]:
import pandas as pd

#r dilinde 2005 yılında bulunup pythona ekledik
seriler ve dataframe

In [2]:
seri=pd.Series([1,2,3,4])
seri      # index nosunu da yazdı

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
type(seri)

pandas.core.series.Series

In [4]:
seri.dtype

dtype('int64')

In [5]:
seri.mean()  #aritmetik ortalama

2.5

In [6]:
seri.axes   # başlangıç,bitiş

[RangeIndex(start=0, stop=4, step=1)]

In [7]:
seri.size

4

In [8]:
seri.ndim  #boyut

1

In [9]:
seri.shape  # 4 satır

(4,)

In [14]:
seri.head(2)  # başlangıç

0    1
1    2
dtype: int64

In [11]:
seri.tail(2)  # son 2 değer

2    3
3    4
dtype: int64

In [12]:
seri.tail()  # son

0    1
1    2
2    3
3    4
dtype: int64

In [15]:
import numpy as np

In [16]:
seri=pd.Series(np.random.randint(3,17,size=20))
seri

0      9
1     11
2     12
3      6
4     12
5      7
6      3
7      6
8      7
9      5
10     5
11     7
12    15
13     8
14     8
15    13
16    16
17     3
18     5
19     5
dtype: int32

In [17]:
seri=pd.Series(np.random.randint(1,10,size=5))
seri

0    6
1    9
2    9
3    8
4    3
dtype: int32

In [18]:
seri.index=["a","b","c","d","e"]
seri

a    6
b    9
c    9
d    8
e    3
dtype: int32

In [17]:
seri["a":"c"]  # bu aralıktakiler

a    7
b    9
c    7
dtype: int32

In [18]:
seri

a    7
b    9
c    7
d    6
e    1
dtype: int32

In [19]:
seri["c":"e"]   # c ve e dahil getirdi

c    7
d    6
e    1
dtype: int32

In [19]:
seri1=pd.Series(np.random.randint(3,100, size=5))
seri2=pd.Series(np.random.randint(4,200, size=5))

In [23]:
seri3=pd.concat([seri1,seri2])
seri3        #index nosu 0 dan sonra tekrar 0 dan

0     75
1     99
2     77
3     38
4     84
0    164
1     56
2    161
3     17
4     45
dtype: int32

In [28]:
seri1=pd.Series(np.random.randint(3,100, size=5))
seri2=pd.Series(np.random.randint(4,200, size=10))
seri

a    6
b    9
c    9
d    8
e    3
dtype: int32

In [24]:
seri3=pd.concat([seri1,seri2],ignore_index=True)
seri3              # size önemli değil  veee ignore index düzenler............

0      7
1     39
2     96
3     84
4     95
0     37
1     93
2    180
3    150
4    112
5    128
6    125
7     95
8     57
9     53
dtype: int32

In [25]:
seri.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [26]:
seri.keys

<bound method Series.keys of a    6
b    9
c    9
d    8
e    3
dtype: int32>

In [27]:
seri.values

array([6, 9, 9, 8, 3])

In [ ]:
list(seri.items())

In [ ]:
8 in seri.values

In [ ]:
"a" in seri

In [26]:
sözlük={"hello":"merhaba","age":"yaş","computer":"bilgisayar"}
seri=pd.Series(sözlük)
seri

hello          merhaba
age                yaş
computer    bilgisayar
dtype: object

In [ ]:
seri.values

In [ ]:
seri.keys

In [ ]:
seri

In [ ]:
list(seri.items())

In [ ]:
seri=pd.Series(np.arange(1,10,2))
seri

In [ ]:
seri.std()      # standart sapma

In [ ]:
seri.var()     # varyans sapma

In [ ]:
seri.median()  #ortadaki sayı 

In [ ]:
seri=pd.Series(np.random.randint(3,100,size=9))
seri

In [ ]:
seri.mean()

In [ ]:
seri.median()

In [ ]:
seri.sort_values()

In [ ]:
seri.sort_values().median()  #ortadaki sayı tekse çiftse ortası yine

In [ ]:
seri

#### dataFrame veri için önemli

In [27]:
df=pd.DataFrame(np.random.randint(1,100,size=10))
df

0
0  23
1   9
2  50
3  39
4  75
5  88
6  17
7  95
8  33
9  51

In [28]:
df=pd.DataFrame(np.random.randint(1,100,size=10),columns=["değer"])
df

değer
0     95
1     20
2     40
3     81
4     87
5     54
6     31
7     92
8     36
9     11

In [29]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,4)))
df

0   1   2   3
0  14  32  15  47
1  64  53  13  34
2  97  33  83   6

In [30]:
df=pd.DataFrame(np.random.randint(1,100,size=(4,5)),
index=["a","b","c","d"],columns=["deg1","deg2","deg3","deg4","deg5"])
df

deg1  deg2  deg3  deg4  deg5
a    62    36    39    17     9
b    31    59    80    82    15
c    81    73    91    85    62
d    68    37     1    54    83

In [31]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.dtypes   # object olarak aldı

In [ ]:
df.axes  # index ve colonları

In [ ]:
df.size

In [ ]:
df.shape

In [ ]:
df.ndim  # 2 boyut

In [32]:
df.values   # arraya çevirdi listeye çevirdi

array([[62, 36, 39, 17,  9],
       [31, 59, 80, 82, 15],
       [81, 73, 91, 85, 62],
       [68, 37,  1, 54, 83]])

In [33]:
df

deg1  deg2  deg3  deg4  deg5
a    62    36    39    17     9
b    31    59    80    82    15
c    81    73    91    85    62
d    68    37     1    54    83

In [ ]:
df.head(3)  # ilk üç satır

In [35]:
df.tail(3)  # son üç satır

deg1  deg2  deg3  deg4  deg5
b    31    59    80    82    15
c    81    73    91    85    62
d    68    37     1    54    83

In [38]:
s1=np.random.randint(1,100,size=5)
s2=np.random.randint(1,100,size=5)
s3=np.random.randint(1,100,size=5)

In [36]:
number={"var1":s1,"var2":s2,"var3":s3}

In [39]:
df=pd.DataFrame(number)
df

var1  var2  var3
0    66    48    16
1    28    64    73
2    20    59    53
3    93    85    94
4    47    74    91

In [40]:
df=pd.DataFrame(number,index=[list("abcde")])
df                           # abcde yi atadı

var1  var2  var3
a    66    48    16
b    28    64    73
c    20    59    53
d    93    85    94
e    47    74    91

In [41]:
df["var1"].mean()

50.8

In [42]:
df

var1  var2  var3
a    66    48    16
b    28    64    73
c    20    59    53
d    93    85    94
e    47    74    91

In [43]:
df[0:2]

var1  var2  var3
a    66    48    16
b    28    64    73

df[1,2]    # 1. satır 2. sütün olmadı

In [44]:
df.iloc[0]   # ilk satırı getirdi, sayısal verileri

var1    66
var2    48
var3    16
Name: (a,), dtype: int32

In [46]:
df.iloc[[0]]   #  dataframe şeklinde satır sayısı

var1  var2  var3
a    66    48    16

In [45]:
df.loc["b":"d"]  # d yi getirdi index nosuna göre  önemliiiiiiiii

var1  var2  var3
b    28    64    73
c    20    59    53
d    93    85    94

In [47]:
df.iloc[[3]]             # integer locasyon

var1  var2  var3
d    93    85    94

In [48]:
df.loc[["d"]] 
# indexte  locasyon

var1  var2  var3
d    93    85    94

In [49]:
df.iloc[2:4,1:3]          #satır ve sütün

var2  var3
c    59    53
d    85    94

In [50]:
df.loc["c":"d","var2":"var3"] # locta int yok index ve colon noları

var2  var3
c    59    53
d    85    94

In [51]:
df.isnull()                  #null değer yok

var1   var2   var3
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False
e  False  False  False

In [52]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,4)))
df

0   1   2   3
0   7  54   5  35
1  21  29  45  80
2  20  94  92  19

In [53]:
df.drop(0, axis=0) # kalıcı silmez  ilk satır

0   1   2   3
1  21  29  45  80
2  20  94  92  19

In [54]:
df.drop(1) # kalıcı silmez  ilk satır

0   1   2   3
0   7  54   5  35
2  20  94  92  19

In [55]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,3)))
df

0   1   2
0  67  78  77
1   4  18  24
2  87  61  64

In [56]:
df.drop(1,axis=0)  # 1. satır    axis 0 satır

0   1   2
0  67  78  77
2  87  61  64

In [58]:
df.drop(1,axis=1)   #1. sütün    axis 1 sütün

0   2
0  67  77
1   4  24
2  87  64

In [59]:
a=np.random.randint(3,20, size=(3,3))
b=np.random.randint(2,100, size=(5,3))

In [60]:
a

array([[10, 18, 15],
       [14, 18, 13],
       [17, 12,  3]])

In [61]:
b

array([[61, 46, 92],
       [92, 17, 21],
       [30, 53, 30],
       [ 8, 89, 94],
       [32, 61, 60]])

In [62]:
c=np.concatenate([a,b])
c

array([[10, 18, 15],
       [14, 18, 13],
       [17, 12,  3],
       [61, 46, 92],
       [92, 17, 21],
       [30, 53, 30],
       [ 8, 89, 94],
       [32, 61, 60]])

In [63]:
df=pd.DataFrame(c,columns=[list("abc")])
df                            

a   b   c
0  10  18  15
1  14  18  13
2  17  12   3
3  61  46  92
4  92  17  21
5  30  53  30
6   8  89  94
7  32  61  60

In [64]:
df.iloc[2,1]

12

In [66]:
df.loc[2,"b"]

b    12
Name: 2, dtype: int32

In [65]:
df.drop(0)

a   b   c
1  14  18  13
2  17  12   3
3  61  46  92
4  92  17  21
5  30  53  30
6   8  89  94
7  32  61  60

In [67]:
df.drop("c",axis=1) # c sütünü sil sütün tamamı axis...

a   b
0  10  18
1  14  18
2  17  12
3  61  46
4  92  17
5  30  53
6   8  89
7  32  61

In [94]:
df

a   b   c
0  10  18  15
1  14  18  13
2  17  12   3
3  61  46  92
4  92  17  21
5  30  53  30
6   8  89  94
7  32  61  60

In [93]:
import numpy as nm
import pandas as pd

In [72]:
df.loc[0].sum() # satır topladık

43

In [80]:
df.iloc[:,1].sum() # sütün toplamı

314

In [83]:
df[df>15]

a     b     c
0   NaN  18.0   NaN
1   NaN  18.0   NaN
2  17.0   NaN   NaN
3  61.0  46.0  92.0
4  92.0  17.0  21.0
5  30.0  53.0  30.0
6   NaN  89.0  94.0
7  32.0  61.0  60.0

In [101]:
df>15  # true false dönderir

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3   True   True   True
4   True   True   True
5   True   True   True
6  False   True   True
7   True   True   True

In [109]:
df=pd.DataFrame(np.random.randint(1,100,size=(5,4)))
df

0   1   2   3
0  42  93  77  56
1  75  69  15  91
2  11  57  26  30
3  16  33  86  18
4  54  76  70  45

In [111]:
df[df[1:2]>45] # 1. satır da 45 den büyük

0     1   2     3
0   NaN   NaN NaN   NaN
1  75.0  69.0 NaN  91.0
2   NaN   NaN NaN   NaN
3   NaN   NaN NaN   NaN
4   NaN   NaN NaN   NaN

In [112]:
df[df[1:5]>45]

0     1     2     3
0   NaN   NaN   NaN   NaN
1  75.0  69.0   NaN  91.0
2   NaN  57.0   NaN   NaN
3   NaN   NaN  86.0   NaN
4  54.0  76.0  70.0   NaN

In [113]:
df

0   1   2   3
0  42  93  77  56
1  75  69  15  91
2  11  57  26  30
3  16  33  86  18
4  54  76  70  45

In [115]:
df[df[3]>80]

0   1   2   3
1  75  69  15  91

In [120]:
df.iloc[2]

0    11
1    57
2    26
3    30
Name: 2, dtype: int32

In [124]:
df[df[3]>55] #indexlerken sütüna göre süzdü

0   1   2   3
0  42  93  77  56
1  75  69  15  91

In [129]:
df

0   1   2   3
0  42  93  77  56
1  75  69  15  91
2  11  57  26  30
3  16  33  86  18
4  54  76  70  45

In [133]:
df.iloc[[2,1] and [3,2]]

0   1   2   3
3  16  33  86  18
2  11  57  26  30

In [128]:
df[(df[3]>55) & (df[2]<25)] # ve işareti

0   1   2   3
1  75  69  15  91

In [135]:
df1=pd.DataFrame({"çalışanlar":["ali","veli","mahmut"],"işe başlama":[2021,2022,2023]})
df2=pd.DataFrame({"çalışanlar":["ali","veli","mahmut"],"departman":["ik","it","muh"]})

In [138]:
pd.merge(df1,df2) # merge etti

çalışanlar  işe başlama departman
0        ali         2021        ik
1       veli         2022        it
2     mahmut         2023       muh

In [139]:
df3=pd.merge(df1,df2)

In [140]:
df3

çalışanlar  işe başlama departman
0        ali         2021        ik
1       veli         2022        it
2     mahmut         2023       muh

In [142]:
df4=pd.DataFrame({"grup":["mühendis","İT_uzmanı","çaycı"],"çalışanlar":["ali","veli","mahmut"]})

In [143]:
df4

grup çalışanlar
0   mühendis        ali
1  İT_uzmanı       veli
2      çaycı     mahmut

In [144]:
pd.merge(df3,df4)

çalışanlar  işe başlama departman       grup
0        ali         2021        ik   mühendis
1       veli         2022        it  İT_uzmanı
2     mahmut         2023       muh      çaycı