In [71]:
import numpy as np

In [72]:
np.__version__

'1.19.2'

In [73]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [74]:
a=np.array((1,2,3,4,5)) #tuple olarak içine koyduk array nesnesi oldu
a

array([1, 2, 3, 4, 5])

In [75]:
np.array([[1,2,3,4],[2,5,8,9],[9,8,9,10]])

array([[ 1,  2,  3,  4],
       [ 2,  5,  8,  9],
       [ 9,  8,  9, 10]])

In [76]:
arr = np.array(55)
arr              # boyutsuz

array(55)

In [77]:
arr = np.array([1, 2, 3, 4, 5])
arr               # 1 boyutlu

array([1, 2, 3, 4, 5])

In [78]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr              # 2 boyutlu

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [80]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)  # 0 boyutsuz dimension
print(b.ndim)  # 1 boyutlu 1 parantez 
print(c.ndim)  # 2 boyutlu 2 parantez
print(d.ndim)  # 3 boyutlu 3 parantez

0
1
2
3


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr                    # beş boyutlu n dimensions  ndmin

array([[[[[1, 2, 3, 4]]]]])

In [20]:
a= np.array([1,3], ndmin=5)
a

array([[[[[1, 3]]]]])

In [21]:
arr = np.array([1, 2, 3, 4])

arr[2] + arr[3]  # topladı normal

7

In [24]:
arr = np.array([1, 2, 3, 4])
bar=np.array([5, 10, 20, 30])
c=np.concatenate([arr,bar])  # extend ekledi
c

array([ 1,  2,  3,  4,  5, 10, 20, 30])

In [26]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[0,1]  # 0. satır 1. sütün

2

In [27]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 56]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 0, 2])

3


In [30]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])  #2 3 4 5 ikişerli olunca 0. 2.

[2 4]


In [35]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [37]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [38]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) # her iki satırın 2. kolonları

[3 8]


In [39]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under
quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 

In [ ]:
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [41]:
arr = np.array(list("abcdef"))
arr.dtype

<U1


In [43]:
arr

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [45]:
arr = np.array(['apple', 'abbbbbbbbanana', 'cherry'],dtype=str)
arr.dtype   # 14 oldu

dtype('<U14')

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) # default değer  s

In [46]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [47]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [50]:
arr = np.array(['a', 2, 3], dtype='str')
arr                       # str yaptık

array(['a', '2', '3'], dtype='<U1')

In [24]:
arr = np.array([1.0, 8.6, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 8 3]
int32


In [25]:
arr = np.array([1.1, 6.9, 3.1])

newarr = arr.astype("i8") # integer 8 byte

print(newarr)
print(newarr.dtype)

[1 6 3]
int64


In [58]:
arr = np.array([1, 0, 3])

new=arr.astype(bool)
new

array([ True, False,  True])

In [60]:
new_arr=np.array(arr,dtype="bool")
new_arr

array([ True, False,  True])

In [2]:
import numpy as np

In [47]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

In [48]:
arr

array([42,  2,  3,  4,  5])

In [49]:
x      #copy de 2. kopya aldı

array([1, 2, 3, 4, 5])

In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

In [27]:
arr

array([42,  2,  3,  4,  5])

In [28]:
x

array([42,  2,  3,  4,  5])

In [30]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

In [33]:
arr

array([31,  2,  3,  4,  5])

In [32]:
x

array([31,  2,  3,  4,  5])

In [35]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

In [46]:
x.base  # The copy returns None.

In [36]:
y.base  #The view returns the original array.

array([1, 2, 3, 4, 5])

In [ ]:
#shape

In [16]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
arr=np.array([2,3,4,5,6])
arr

array([2, 3, 4, 5, 6])

In [42]:
a=np.array([2,3,6,5.0,8])  # bir float varsa hepsi float
a

array([2., 3., 6., 5., 8.])

In [43]:
a.dtype  # cinsine baktık float

dtype('float64')

In [44]:
b=np.array([12,15,16,18]).astype("S")
b

array([b'12', b'15', b'16', b'18'], dtype='|S11')

In [45]:
b.dtype

dtype('S11')

In [4]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
x

array([1, 2, 3, 4, 5])

In [6]:
arr

array([42,  2,  3,  4,  5])

In [9]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 100

In [10]:
x

array([100,   2,   3,   4,   5])

In [11]:
arr

array([100,   2,   3,   4,   5])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

In [14]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) # tuple 
print(arr)
print(arr.ndim)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
2


In [17]:
rr = np.array([1, 2, 3, 4], ndmin=5)

print(rr)
print('shape of array :', arr.shape)
print(rr[0]) # bir daralttı

[[[[[1 2 3 4]]]]]
shape of array : (2, 4)
[[[[1 2 3 4]]]]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # 2 ye böl,2 satır 3 sütun yap
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

In [20]:
print(arr.base)

None


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1) # 2 ye böl 2 satır kalanı (-1) kendin doldur
newarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)  # kalıcı değil...
newarr            # düz hal seri hale -1

array([1, 2, 3, 4, 5, 6])

### iteration

In [27]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [39]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [41]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]],ndmin=10)

for x in np.nditer(arr): # tek hale getir kök dizinee kadar aç
  print(x)

1
2
3
4
5
6
7
8


In [46]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [47]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [48]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [49]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for a, x in np.ndenumerate(arr):  # çok güzel indexlerini verdi
  print(a, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [50]:
### joın

In [51]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [52]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [53]:
arr1

array([[1, 2],
       [3, 4]])

In [54]:
arr2

array([[5, 6],
       [7, 8]])

In [55]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [58]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)  # önemli karışmasın

[[1 4]
 [2 5]
 [3 6]]


In [60]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2)) # horizontal yatayda 

print(arr)

[1 2 3 4 5 6]


In [61]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))# colon olarak

print(arr)

[[1 2 3]
 [4 5 6]]


In [62]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2)) #

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [63]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)          # 3 e ayırdı

[array([1, 2]), array([3, 4]), array([5, 6])]


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)         # 4 e ayırdı

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [66]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [67]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)  # sütünü bölmüş

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [70]:
# Similar alternates to vstack() and dstack() 
# are available as vsplit() and dsplit().

SyntaxError: invalid syntax (<ipython-input-70-73c12fb44170>, line 1)