In [2]:
import numpy as np

########random randint arange  1 satır 1 sütün tek boyutlu

In [4]:
a=[1,3,5,7]
b=[2,4,6,8]
c=[3,6,9,12]
a=np.array(a)
b=np.array(b)
c=np.array(c)
d=a*b*c
d=list(d)
d           # index olarak çarptı

[6, 72, 270, 672]

In [6]:
d=np.array([3.14,14,15,16])  # bir tane varsa float hepsi oldu

In [7]:
type(d)

numpy.ndarray

In [9]:
d.dtype  # float değer tuttu hepsini   # tüm değerler float 64

dtype('float64')

In [10]:
d # diğer değerlerde floata çevrilip tutulur

array([ 3.14, 14.  , 15.  , 16.  ])

In [11]:
np.array([2,4,6,8],dtype=str) # str olarak atadı

array(['2', '4', '6', '8'], dtype='<U1')

In [12]:
np.array([2,4,6,8],dtype=int) #int yaptık

array([2, 4, 6, 8])

In [13]:
np.array([2,4,6,8],dtype=float)  #int yaptık  tek boyutlu

array([2., 4., 6., 8.])

In [14]:
np.zeros(5,dtype=int)  #int yaptık   tek boyutlu  000

array([0, 0, 0, 0, 0])

In [15]:
np.ones(6,dtype=int)  #1 oluşturduk tek boyutlu  111

array([1, 1, 1, 1, 1, 1])

In [17]:
np.random.randint(3,6,size=5) # 3 ila 6 arasında 5 tane int sayı

array([3, 5, 4, 5, 4])

In [16]:
np.arange(5,10)  # birer birer arttı

array([5, 6, 7, 8, 9])

In [3]:
np.arange(5,11,2) # 2 şer arttı son sayı dahil değil

array([5, 7, 9])

In [7]:
np.arange(3,13).reshape(2,5)  # 2 satır 5 sütün random yok
# kendimiz belirledik aralığı *****arange reshape*** size uyacak

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [8]:
np.random.randint(3,9,size=(2,4)) # 2 satır 5 sütün çok sütünlü matris
                      # size biz verdik

array([[3, 8, 7, 4],
       [3, 3, 8, 4]])

In [11]:
np.random.randint(3,23,size=(5,4))

array([[21, 10,  7,  6],
       [ 6, 12, 15,  9],
       [18, 22, 10,  4],
       [ 4, 17, 14, 21],
       [ 7,  8, 17, 14]])

In [33]:
a=np.arange(1,16,2)
a       # tek boyutluydu

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [34]:
a.reshape(2,4)   # çift boyutlu reshape

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [ ]:
# concatenate:

In [14]:
a=np.random.randint(1,6,size=5)
b=np.random.randint(2,7,size=5)

In [15]:
a

array([3, 4, 4, 2, 2])

In [16]:
b

array([2, 4, 2, 6, 6])

In [17]:
c=np.concatenate([a,b])  # birleştirdi extend
c

array([3, 4, 4, 2, 2, 2, 4, 2, 6, 6])

In [18]:
c=a+b   # concatenate yanyana yazar
c  #toplamlarını verdi toplayamdı aynı listede

array([5, 8, 6, 8, 8])

In [20]:
a=np.random.randint(2,7,size=4)  # size ları farklı olsada aynı yere getirdi
b=np.random.randint(10,14,size=6)

In [21]:
b

array([12, 13, 10, 12, 13, 10])

In [24]:
c=np.concatenate([a,b]) 
c

array([ 3,  4,  4,  4, 12, 13, 10, 12, 13, 10])

In [34]:
a=np.random.randint(2,7,size=(3,3))  # sütün aynı olacak
b=np.random.randint(8,14,size=(3,3))  # concaenate sütün bazlı birleştirdi
c=np.concatenate([a,b])
c

array([[ 2,  5,  5],
       [ 4,  4,  5],
       [ 3,  2,  6],
       [10,  9, 10],
       [13, 13, 11],
       [11, 10,  8]])

In [35]:
a

array([[2, 5, 5],
       [4, 4, 5],
       [3, 2, 6]])

In [36]:
c=np.concatenate([a,b],axis=1) # satır sayısını baz aldı 3 satırdı yaaa
c                               # satır bazında birleşti ST DEĞ

array([[ 2,  5,  5, 10,  9, 10],
       [ 4,  4,  5, 13, 13, 11],
       [ 3,  2,  6, 11, 10,  8]])

In [39]:
c=np.concatenate([a,b],axis=0) #  sütün sayısını baz aldı
c                              # axis önemli   3 sütündü yaaa
                               # default axis 000 S DEĞ

array([[ 2,  5,  5],
       [ 4,  4,  5],
       [ 3,  2,  6],
       [10,  9, 10],
       [13, 13, 11],
       [11, 10,  8]])

In [72]:
# axis=0 yani sütünü eşit al sütün temelli birleştir.
a=np.random.randint(2,7,size=(2,6))  
b=np.random.randint(8,14,size=(3,6))
c=np.concatenate([a,b],axis=0)  # S DEĞ
c

array([[ 5,  6,  4,  2,  6,  2],
       [ 4,  4,  4,  4,  5,  5],
       [ 9,  9, 13, 13,  8, 12],
       [10,  8, 12,  9,  9, 11],
       [ 8, 13, 13,  8, 12, 12]])

In [73]:
c.ndim      #boyut nedir

2

In [74]:
c.size     #eleman sayısı

30

In [75]:
c.shape   # kaç satır kaç sütün

(5, 6)

In [76]:
c.mean()   # aritmetik ortalamasını verir

8.0

In [77]:
c.std()   # standart sapması nedir

3.5023801430836525

In [78]:
c.var()   #  varyans değeri standart sapmanın karesi

12.266666666666667

###### Stantart sapma hesaplamak için;/
Sayıların aritmetik ortalaması hesaplanır./
Her bir sayının aritmetik ortalamadan farkı bulunur./
Bulunan farkların her birinin karesi hesaplanır./
Farkların kareleri toplanır./
Elde edilen toplam, serinin eleman sayısının bir eksiğine bölünür./

In [41]:
np.sort(c)   #  sıraladı axis 0 satır ve sütün bazında

array([[ 2,  5,  5],
       [ 4,  4,  5],
       [ 2,  3,  6],
       [ 9, 10, 10],
       [11, 13, 13],
       [ 8, 10, 11]])

In [42]:
np.sort(c,axis=0)   # sütün bazında

array([[ 2,  2,  5],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [10,  9,  8],
       [11, 10, 10],
       [13, 13, 11]])

In [84]:
np.sort(c,axis=1)   # satır bazında

array([[ 2,  2,  4,  5,  6,  6],
       [ 4,  4,  4,  4,  5,  5],
       [ 8,  9,  9, 12, 13, 13],
       [ 8,  9,  9, 10, 11, 12],
       [ 8,  8, 12, 12, 13, 13]])

In [85]:
a

array([[5, 6, 4, 2, 6, 2],
       [4, 4, 4, 4, 5, 5]])

In [ ]:
a[0]          # ilk satırı verir

In [86]:
a[-1]         # son satırı verir

array([4, 4, 4, 4, 5, 5])

In [87]:
a[1]          # ikinci satırı verir

array([4, 4, 4, 4, 5, 5])

In [88]:
a[1,1]       #1.satır 1. sütün

4

In [91]:
a[0:2,2]     # sol satır sağ sütün

array([4, 4])

In [ ]:
a[0:2,0:2]   #ilk iki satırdaki 3 sütünü getir

In [43]:
a=np.copy(b) # bir numpy kopyaladık
b

array([[10,  9, 10],
       [13, 13, 11],
       [11, 10,  8]])

In [94]:
d=np.copy(b)
b[2,2]=3

array([[ 9,  9, 13, 13,  8, 12],
       [10,  8, 12,  9,  9, 11],
       [ 8, 13, 13,  8, 12, 12]])

In [97]:
d[1,1]=1
d

array([[ 9,  9, 13, 13,  8, 12],
       [10,  1, 12,  9,  9, 11],
       [ 8, 13, 13,  8, 12, 12]])

In [98]:
b

array([[ 9,  9, 13, 13,  8, 12],
       [10,  8, 12,  9,  9, 11],
       [ 8, 13, 13,  8, 12, 12]])

In [99]:
a>12  # a nın 12 de büyük olanalrını döndür 

array([[False, False,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True, False, False, False]])

In [100]:
a[a>11] # fency methodu a nın 11 den büyük elemannlarını getir

array([13, 13, 12, 12, 13, 13, 12, 12])

In [101]:
len(a[a>12]) # 12 den büyük kaç değer var

4

In [107]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [108]:
a[0:2]>7

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [111]:
a

array([[ 9,  9, 13, 13,  8, 12],
       [10,  8, 12,  9,  9, 11],
       [ 8, 13, 13,  8, 12, 12]])

In [113]:
np.add(a,13) # her elemana 13 ekledi

array([[22, 22, 26, 26, 21, 25],
       [23, 21, 25, 22, 22, 24],
       [21, 26, 26, 21, 25, 25]])

In [114]:
np.subtract(a,5) # her elemandan 5 çıkardı

array([[4, 4, 8, 8, 3, 7],
       [5, 3, 7, 4, 4, 6],
       [3, 8, 8, 3, 7, 7]])

In [115]:
np.multiply(a,3) # her elemanı 5 ile çarp

array([[27, 27, 39, 39, 24, 36],
       [30, 24, 36, 27, 27, 33],
       [24, 39, 39, 24, 36, 36]])

In [ ]:
np.divide(a,2)  # asıl verileri 2 ye böl

In [116]:
np.mod(a,3)   # mod alma

array([[0, 0, 1, 1, 2, 0],
       [1, 2, 0, 0, 0, 2],
       [2, 1, 1, 2, 0, 0]], dtype=int32)

In [117]:
np.absolute(a)  # mutlak değer

array([[ 9,  9, 13, 13,  8, 12],
       [10,  8, 12,  9,  9, 11],
       [ 8, 13, 13,  8, 12, 12]])

In [118]:
np.cos(a[0]) #ilk satır cosinüs değerleri

array([-0.91113026, -0.91113026,  0.90744678,  0.90744678, -0.14550003,
        0.84385396])

In [120]:
np.sin(a[1]) #2. satır sinüs değerleri

array([-0.54402111,  0.98935825, -0.53657292,  0.41211849,  0.41211849,
       -0.99999021])

In [121]:
np.tan(a)   #a nın tanant değerleri

array([[  -0.45231566,   -0.45231566,    0.46302113,    0.46302113,
          -6.79971146,   -0.63585993],
       [   0.64836083,   -6.79971146,   -0.63585993,   -0.45231566,
          -0.45231566, -225.95084645],
       [  -6.79971146,    0.46302113,    0.46302113,   -6.79971146,
          -0.63585993,   -0.63585993]])

In [122]:
np.log(a[1,2]) #logaritma

2.4849066497880004

In [123]:
np.log10(a[1]) # 10 luk tabanda

array([1.        , 0.90308999, 1.07918125, 0.95424251, 0.95424251,
       1.04139269])

In [124]:
np.sqrt(16)  #karekökü

4.0

In [126]:
np.power(4,2)  #üssünü aldı

16

In [127]:
np.power(a,2)  # a nın karesi

array([[ 81,  81, 169, 169,  64, 144],
       [100,  64, 144,  81,  81, 121],
       [ 64, 169, 169,  64, 144, 144]], dtype=int32)

In [128]:
np.power(a,a)  # a  a üssü karesi

array([[  387420489,   387420489, -1692154371, -1692154371,    16777216,
         -251658240],
       [ 1410065408,    16777216,  -251658240,   387420489,   387420489,
         1843829075],
       [   16777216, -1692154371, -1692154371,    16777216,  -251658240,
         -251658240]], dtype=int32)

In [ ]:
pynative numpy