In [1]:
import numpy as np

########random randint arange  1 satır 1 sütün tek boyutlu

In [2]:
a=[1,3,5,7]
b=[2,4,6,8]
c=[3,6,9,12]
a=np.array(a)
b=np.array(b)
c=np.array(c)
d=a*b*c
d=list(d)
d           # index olarak çarptı

[6, 72, 270, 672]

In [3]:
d=np.array([3.14,14,15,16])  # bir tane varsa float hepsi oldu

In [4]:
type(d)

numpy.ndarray

In [5]:
d.dtype  # float değer tuttu hepsini   # tüm değerler float 64

dtype('float64')

In [6]:
d # diğer değerlerde floata çevrilip tutulur

array([ 3.14, 14.  , 15.  , 16.  ])

In [7]:
np.array([2,4,6,8],dtype=str) # str olarak atadı

array(['2', '4', '6', '8'], dtype='<U1')

In [8]:
np.array([2,4,6,8],dtype=int) #int yaptık

array([2, 4, 6, 8])

In [9]:
np.array([2,4,6,8],dtype=float)  #int yaptık  tek boyutlu

array([2., 4., 6., 8.])

In [10]:
np.zeros(5,dtype=int)  #int yaptık   tek boyutlu  000

array([0, 0, 0, 0, 0])

In [11]:
np.ones(6,dtype=int)  #1 oluşturduk tek boyutlu  111

array([1, 1, 1, 1, 1, 1])

In [12]:
np.random.randint(3,6,size=5) # 3 ila 6 arasında 5 tane int sayı

array([5, 3, 3, 5, 5])

In [13]:
np.arange(5,10)  # birer birer arttı

array([5, 6, 7, 8, 9])

In [14]:
np.arange(5,11,2) # 2 şer arttı son sayı dahil değil

array([5, 7, 9])

In [15]:
np.arange(3,13).reshape(2,5)  # 2 satır 5 sütün random yok
# kendimiz belirledik aralığı *****arange reshape*** size uyacak

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [16]:
np.random.randint(3,9,size=(2,4)) # 2 satır 5 sütün çok sütünlü matris
                      # size biz verdik

array([[4, 8, 4, 7],
       [7, 8, 4, 5]])

In [17]:
np.random.randint(3,23,size=(5,4))

array([[ 7, 14,  5,  5],
       [20, 11,  6, 19],
       [16, 16,  4, 21],
       [15,  4, 11, 13],
       [12, 22,  7, 19]])

In [18]:
a=np.arange(1,16,2)
a       # tek boyutluydu

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [19]:
a.reshape(2,4)   # çift boyutlu reshape

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [20]:
# concatenate:

In [21]:
a=np.random.randint(1,6,size=5)
b=np.random.randint(2,7,size=5)

In [22]:
a

array([2, 2, 1, 2, 3])

In [23]:
b

array([2, 3, 2, 6, 3])

In [24]:
c=np.concatenate([a,b])  # birleştirdi extend
c

array([2, 2, 1, 2, 3, 2, 3, 2, 6, 3])

In [25]:
c=a+b   # concatenate yanyana yazar
c  #toplamlarını verdi toplayamdı aynı listede

array([4, 5, 3, 8, 6])

In [26]:
a=np.random.randint(2,7,size=4)  # size ları farklı olsada aynı yere getirdi
b=np.random.randint(10,14,size=6)

In [27]:
b

array([11, 13, 12, 12, 11, 11])

In [28]:
c=np.concatenate([a,b]) 
c

array([ 3,  4,  4,  5, 11, 13, 12, 12, 11, 11])

In [77]:
a=np.random.randint(2,7,size=(3,3))  # sütün aynı olacak
b=np.random.randint(8,14,size=(3,3))  # concaenate sütün bazlı birleştirdi
c=np.concatenate([a,b])
c

array([[ 6,  6,  2],
       [ 3,  6,  4],
       [ 6,  5,  3],
       [12,  8,  8],
       [13, 12,  8],
       [10,  9, 12]])

In [80]:
a

array([[6, 6, 2],
       [3, 6, 4],
       [6, 5, 3]])

In [81]:
c=np.concatenate([a,b],axis=1) # satır sayısını baz aldı 3 satırdı yaaa
c                               # satır bazında birleşti ST DEĞ

array([[ 6,  6,  2, 12,  8,  8],
       [ 3,  6,  4, 13, 12,  8],
       [ 6,  5,  3, 10,  9, 12]])

In [82]:
c=np.concatenate([a,b],axis=0) #  sütün sayısını baz aldı
c                              # axis önemli   3 sütündü yaaa
                               # default axis 000 S DEĞ

array([[ 6,  6,  2],
       [ 3,  6,  4],
       [ 6,  5,  3],
       [12,  8,  8],
       [13, 12,  8],
       [10,  9, 12]])

In [83]:
# axis=0 yani sütünü eşit al sütün temelli birleştir.
a=np.random.randint(2,7,size=(2,6))  
b=np.random.randint(8,14,size=(3,6))
c=np.concatenate([a,b],axis=0)  # S DEĞ
c

array([[ 3,  3,  3,  4,  4,  6],
       [ 4,  6,  6,  2,  5,  5],
       [13, 12,  9, 12,  9, 10],
       [12, 12, 11,  8, 10,  8],
       [11, 12,  9,  8, 11, 12]])

In [85]:
c.ndim      #boyut nedir

2

In [86]:
c.size     #eleman sayısı

30

In [87]:
c.shape   # kaç satır kaç sütün

(5, 6)

In [88]:
c.mean()   # aritmetik ortalamasını verir

8.0

In [89]:
c.std()   # standart sapması nedir

3.40587727318528

In [90]:
c.var()   #  varyans değeri standart sapmanın karesi

11.6

###### Stantart sapma hesaplamak için;/
Sayıların aritmetik ortalaması hesaplanır./
Her bir sayının aritmetik ortalamadan farkı bulunur./
Bulunan farkların her birinin karesi hesaplanır./
Farkların kareleri toplanır./
Elde edilen toplam, serinin eleman sayısının bir eksiğine bölünür./

In [91]:
np.sort(c)   #  sıraladı default axis 1 sütün sıralar 0,1,2 indexteki

array([[ 3,  3,  3,  4,  4,  6],
       [ 2,  4,  5,  5,  6,  6],
       [ 9,  9, 10, 12, 12, 13],
       [ 8,  8, 10, 11, 12, 12],
       [ 8,  9, 11, 11, 12, 12]])

In [41]:
np.sort(c,axis=0)   # yukarıdan aşağı satırlarının 0.indexlerini sıralar

array([[ 3,  2,  3,  5,  3,  2],
       [ 3,  5,  3,  6,  6,  2],
       [ 8,  8, 10, 10, 12,  8],
       [ 9,  9, 11, 12, 13, 10],
       [11, 13, 13, 13, 13, 13]])

In [42]:
np.sort(c,axis=1)   # sütun sıralar satır sırası önemli değil

array([[ 2,  2,  3,  3,  3,  6],
       [ 2,  3,  3,  5,  5,  6],
       [ 8, 11, 12, 13, 13, 13],
       [ 9, 10, 10, 10, 13, 13],
       [ 8,  8,  9, 11, 12, 13]])

In [43]:
a

array([[3, 2, 3, 6, 3, 2],
       [3, 5, 3, 5, 6, 2]])

In [44]:
a[0]          # ilk satırı verir

array([3, 2, 3, 6, 3, 2])

In [45]:
a[-1]         # son satırı verir

array([3, 5, 3, 5, 6, 2])

In [46]:
a[1]          # ikinci satırı verir

array([3, 5, 3, 5, 6, 2])

In [47]:
a[1,1]       #1.satır 1. sütün

5

In [48]:
a[0:2,2]     # sol satır sağ sütün

array([3, 3])

In [49]:
a[0:2,0:2]   #ilk iki satırdaki 3 sütünü getir

array([[3, 2],
       [3, 5]])

In [105]:
a=np.copy(b) # bir numpy kopyaladık
b

array([[13, 12,  9, 12,  9, 10],
       [12, 12, 11,  8, 10,  8],
       [11, 12,  3,  8, 11, 12]])

In [106]:
d=np.copy(b)
b[2,2]=3
d

array([[13, 12,  9, 12,  9, 10],
       [12, 12, 11,  8, 10,  8],
       [11, 12,  3,  8, 11, 12]])

In [107]:
d[1,1]=1
d

array([[13, 12,  9, 12,  9, 10],
       [12,  1, 11,  8, 10,  8],
       [11, 12,  3,  8, 11, 12]])

In [108]:
b

array([[13, 12,  9, 12,  9, 10],
       [12, 12, 11,  8, 10,  8],
       [11, 12,  3,  8, 11, 12]])

In [109]:
a>12  # a nın 12 de büyük olanalrını döndür (boşta bollll)

array([[ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [110]:
a[a>11] # fancy methodu a nın 11 den büyük [a] olursa [içinde getir]

array([13, 12, 12, 12, 12, 12, 12])

In [113]:
len(a[a>11]) # 12 den büyük kaç değer var

7

In [ ]:
dir(a)

In [58]:
a[0:2]>7

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [59]:
a

array([[11,  8, 13, 13, 12, 13],
       [ 9, 13, 10, 10, 13, 10],
       [ 8,  9, 11, 12, 13,  8]])

In [114]:
np.add(a,13) # add a dakilerin hepisne 13 ekledi

array([[26, 25, 22, 25, 22, 23],
       [25, 25, 24, 21, 23, 21],
       [24, 25, 16, 21, 24, 25]])

In [115]:
np.subtract(a,5) # her elemandan 5 çıkardı

array([[ 8,  7,  4,  7,  4,  5],
       [ 7,  7,  6,  3,  5,  3],
       [ 6,  7, -2,  3,  6,  7]])

In [116]:
np.multiply(a,3) # her elemanı 5 ile çarp

array([[39, 36, 27, 36, 27, 30],
       [36, 36, 33, 24, 30, 24],
       [33, 36,  9, 24, 33, 36]])

In [117]:
np.divide(a,2)  # asıl verileri 2 ye böl

array([[6.5, 6. , 4.5, 6. , 4.5, 5. ],
       [6. , 6. , 5.5, 4. , 5. , 4. ],
       [5.5, 6. , 1.5, 4. , 5.5, 6. ]])

In [118]:
np.mod(a,3)   # mod alma

array([[1, 0, 0, 0, 0, 1],
       [0, 0, 2, 2, 1, 2],
       [2, 0, 0, 2, 2, 0]], dtype=int32)

In [65]:
np.absolute(a)  # mutlak değer

array([[11,  8, 13, 13, 12, 13],
       [ 9, 13, 10, 10, 13, 10],
       [ 8,  9, 11, 12, 13,  8]])

In [119]:
np.cos(a[0]) #ilk satır cosinüs değerleri

array([ 0.90744678,  0.84385396, -0.91113026,  0.84385396, -0.91113026,
       -0.83907153])

In [120]:
np.sin(a[1]) #2. satır sinüs değerleri

array([-0.53657292, -0.53657292, -0.99999021,  0.98935825, -0.54402111,
        0.98935825])

In [121]:
np.tan(a)   #a nın tanjant değerleri

array([[ 4.63021133e-01, -6.35859929e-01, -4.52315659e-01,
        -6.35859929e-01, -4.52315659e-01,  6.48360827e-01],
       [-6.35859929e-01, -6.35859929e-01, -2.25950846e+02,
        -6.79971146e+00,  6.48360827e-01, -6.79971146e+00],
       [-2.25950846e+02, -6.35859929e-01, -1.42546543e-01,
        -6.79971146e+00, -2.25950846e+02, -6.35859929e-01]])

In [122]:
np.log(a[1,2]) #logaritma

2.3978952727983707

In [123]:
np.log10(a[1]) # 10 luk tabanda

array([1.07918125, 1.07918125, 1.04139269, 0.90308999, 1.        ,
       0.90308999])

In [125]:
np.sqrt(256)  #karekökü

16.0

In [126]:
np.power(4,3)  #üssünü aldı

64

In [127]:
np.power(a,2)  # a nın karesi

array([[169, 144,  81, 144,  81, 100],
       [144, 144, 121,  64, 100,  64],
       [121, 144,   9,  64, 121, 144]], dtype=int32)

In [74]:
np.power(a,a)  # a  a üssü karesi

array([[ 1843829075,    16777216, -1692154371, -1692154371,  -251658240,
        -1692154371],
       [  387420489, -1692154371,  1410065408,  1410065408, -1692154371,
         1410065408],
       [   16777216,   387420489,  1843829075,  -251658240, -1692154371,
           16777216]], dtype=int32)

SyntaxError: invalid syntax (<ipython-input-128-d3d201cd2102>, line 1)