In [1]:
import numpy as np

In [2]:
Printing Array

[[64392 31655]
 [32579     0]
 [49248   462]
 [    0     0]]

Printing NumPy array Attributes

Array Shape is:  (4, 2)
Array dimensions are  2
Length of each element of array in bytes is  2

SyntaxError: invalid syntax (<ipython-input-2-987eb064e42d>, line 1)

In [ ]:
a= np.arange(2,20).reshape(3,6)
a

In [ ]:
print("Array Shape is:",a.shape)

In [ ]:
print("Array size of eleman:",a.size)

In [ ]:
print("Array size of dimensions:",a.itemsize) # her karakterin boyutu

In [ ]:
a.dtype

In [ ]:
a= np.arange(2,20).reshape(3,6).dtype=float
a

In [ ]:
Exercise 2: Create a 5X2 integer array from a range 
    between 100 to 200 such that the difference between 
    each element is 10 Creating 5X2 array using 
    numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]

In [ ]:
b=np.arange(100,200,10).reshape(5,2)
b

In [ ]:
Exercise 3: Following is the provided numPy array. 
    return array of items in the third column from 
all rows
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66],
                [77, 88, 99]])
Expected Output:

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing array of items in the third column from all rows
[22 55 88]

In [ ]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66],
                [77, 88, 99]])
sampleArray[:,2]   #tüm satırların 3. sütünları

In [ ]:
4. Return array of odd rows and even columns from below 
numpy array

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
Expected Output:

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]

In [ ]:
s = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [ ]:
s[::2,1::2]  # baştan başla sona git 2 şerli satır
             # 1 den başla sona git 2 şerli git sütün

In [ ]:
s[::2,1::2]  # baştan başla sona git 2 şerli satır
             # 1 den başla sona git 2 şerli git sütün

In [ ]:
Exercise 5: Create a result array by adding the following
two NumPy arrays. Next, modify the result array by 
calculating the square of each element
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
Expected Output:

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]

In [5]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [6]:
c=arrayOne+arrayTwo
c

array([[20, 39, 33],
       [25, 25, 28]])

In [7]:
np.power(c,2)

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

In [8]:
np.sqrt(c)

array([[4.47213595, 6.244998  , 5.74456265],
       [5.        , 5.        , 5.29150262]])

In [ ]:
Exercise 6: Split the array into four equal-sized sub-arrays
    Note: Create an 8X3 integer array from a range between
        10 to 34 such that the difference between each 
        element is 1 and then 
Split the array into four equal-sized sub-arrays.

Expected Output:
Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],[13, 14, 15]]), 
array([[16, 17, 18],[19, 20, 21]]), 
array([[22, 23, 24],[25, 26, 27]]), 
array([[28, 29, 30],[31, 32, 33]])]

In [9]:
a=np.arange(10,34).reshape(8,3)
np.split(a,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [ ]:
Exercise 7: Sort following NumPy array
Case 1: Sort array by the second row
Case 2: Sort the array by the second column
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

In [11]:
a = np.array([[34,43,73],[82,22,12],[53,94,66]])
a

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [12]:
np.sort(a[1])  # axis 1 olduğu için

array([12, 22, 82])

In [13]:
a[1]=np.sort(a[1])
a                   # 1. satırı sort etti ve değişti

array([[34, 43, 73],
       [12, 22, 82],
       [53, 94, 66]])

In [ ]:
Exercise 8: Print max from axis 0 and min from axis 1 from the
    following 2-D array.
sampleArray = numpy.array([[34,43,73],[82,22,12],
                           [53,94,66]])
Expected Output:

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Printing amin Of Axis 1
[34 12 53]

Printing amax Of Axis 0
[82 94 73]

In [17]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [16]:
np.min(sampleArray,axis=0) # x ekseni satırlar

array([34, 22, 12])

In [18]:
np.max(sampleArray,axis=1)  # y ekseni sütünlar

array([73, 82, 94])

In [ ]:
Exercise 9: Delete the second column from a given array and
    insert the following new column in its place.
    sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = numpy.array([[10,10,10]])
Expected Output:

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]

Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]

In [ ]:
sy = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sy

In [ ]:
np.delete(sy,1,axis=1)  # her satırdaki 1. indexi sildi

In [ ]:
sy = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sy

In [ ]:
np.delete(sy,1,axis=0)  # her sütünün 1. indexi sildi

In [ ]:
arr=np.array([[10,10,10]]) # her satırın 1. indexlerine 10 ekledik
np.insert(a,1,arr,axis=1)

In [ ]:
 Create two 2-D arrays and Plot them using matplotlib

In [ ]:
a=np.random.randint(2,20, size=(2,3))
a

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

samplear=np.arange(100,200,10)
samplear=samplear.reshape(5,2)

x=samplear[:,0:1] # satırların tümü 0.index
y=samplear[:,1:2] # satırların tümü 1.index

plt.plot(x,y)
plt.show()