In [4]:
import numpy as np
import pandas as pd

In [5]:
# index,columns,groupby,drop,dropna,head,shape,ndim,sixe,vales,loc,iloc,
# tail,geet_dummies,xs,join,merge,concat   -----en çok kullananlar

In [11]:
datam=[1,2,39,67,90]
datam

[1, 2, 39, 67, 90]

In [10]:
pd.DataFrame(datam,columns=["kolon_adı"])

kolon_adı
0          1
1          2
2         39
3         67
4         90

In [12]:
### creating  a dataframe using a numpy arrays

In [13]:
a=np.arange(1,10).reshape(3,3)

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
pd.DataFrame(a,columns=["var1","var2","var3"])
# pandas df yap

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
pd.DataFrame(data=a,)  # columns yazmamız gerek sırada index vardı

In [18]:
df=pd.DataFrame(a,columns=["var1","var2","var3"])
df

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [20]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [21]:
df.tail()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [22]:
df.sum()

var1    12
var2    15
var3    18
dtype: int64

In [23]:
df.columns  # index obj. dönderir

Index(['var1', 'var2', 'var3'], dtype='object')

In [24]:
df.columns=["new1","new2","new3"]

In [25]:
df

new1  new2  new3
0     1     2     3
1     4     5     6
2     7     8     9

In [26]:
df.size

9

In [27]:
df.shape

(3, 3)

In [28]:
type(df)

pandas.core.frame.DataFrame

In [29]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
type(df.values)

numpy.ndarray

In [ ]:
### creating a dataframe using a dict

In [31]:
s1=np.random.randint(10, size=5)
s2=np.random.randint(10, size=5)
s3=np.random.randint(10, size=5)

In [32]:
s1

array([6, 5, 3, 0, 4])

In [33]:
s2

array([9, 4, 3, 9, 9])

In [34]:
s3

array([6, 6, 2, 7, 5])

In [35]:
mydict={"var1":s1,"var2":s2,"var3":s3}

In [36]:
mydict

{'var1': array([6, 5, 3, 0, 4]),
 'var2': array([9, 4, 3, 9, 9]),
 'var3': array([6, 6, 2, 7, 5])}

In [37]:
df1=pd.DataFrame(mydict)

In [38]:
df1

var1  var2  var3
0     6     9     6
1     5     4     6
2     3     3     2
3     0     9     7
4     4     9     5

In [42]:
pd.read_csv("ornekcsv.csv",delimiter=";") # delimiter önemli

a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [44]:
df1[1:3]

var1  var2  var3
1     5     4     6
2     3     3     2

In [45]:
df1[0]

KeyError: 0

In [47]:
df1

var1  var2  var3
0     6     9     6
1     5     4     6
2     3     3     2
3     0     9     7
4     4     9     5

In [46]:
[i for i in df1.index]

[0, 1, 2, 3, 4]

In [48]:
df1.index=["a","b","c","d","e"]

In [49]:
df1

var1  var2  var3
a     6     9     6
b     5     4     6
c     3     3     2
d     0     9     7
e     4     9     5

In [50]:
df1["b":"d"]  # index adı lunca dahil di

var1  var2  var3
b     5     4     6
c     3     3     2
d     0     9     7

In [51]:
"var2" in df1  # column name üstünden çalışır, features özellik varmı

True

In [52]:
9 in df1  # olmadı

False