# pandas exelden fonksiyonlu hayat pandasla geçer.Tablolar DataFrame

pandas ta indexi biz yapabiliriz, seriler sütundur iki dizi df oluşturur.

In [2]:
import numpy as np
import pandas as pd

In [3]:
### creating a pandas series with basic format

In [4]:
import pandas as pd

In [5]:
pd.Series([10,88,3,4,5,]) # 0kolon şeklinde anlaşılır gösterir

0    10
1    88
2     3
3     4
4     5
dtype: int64

In [6]:
ser=pd.Series([10,88,3,4,5,])

In [7]:
type(ser)

pandas.core.series.Series

In [8]:
ser.dtype

dtype('int64')

In [9]:
ser.values

array([10, 88,  3,  4,  5], dtype=int64)

In [10]:
type(ser.values)

numpy.ndarray

In [11]:
for i in ser.values:  # seri elmanları
    print(i)

10
88
3
4
5


In [12]:
[i for i in ser.values]

[10, 88, 3, 4, 5]

In [13]:
ser.head(2)  # baş default 5

0    10
1    88
dtype: int64

In [14]:
ser.tail(2)# son default 5

3    4
4    5
dtype: int64

In [18]:
pd.Series([i for i in "clarusway"])  # object ise str dir, diğer int, float

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

In [20]:

489## creating pandas series using a "list","numpy-array","dict"

489

In [21]:
labels = ["a", "b", "c"]

my_list = [10, 20, 30]

arr = np.array([10, 20, 30])

d = {"a" : 10, "b" : 20, "c" : 30}


In [23]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [24]:
[10,20,30]

[10, 20, 30]

In [25]:
pd.Series(data=my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [38]:
pd.Series(my_list,labels)

a    10
b    20
c    30
dtype: int64

In [26]:
arr

array([10, 20, 30])

In [27]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int32

In [28]:
d

{'a': 10, 'b': 20, 'c': 30}

In [24]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [29]:
pd.Series(d,["w","c","z"])  # c keyi varsa döndürür

w     NaN
c    30.0
z     NaN
dtype: float64

In [30]:
a=np.nan

In [31]:
a

nan

In [32]:
##data in series

In [33]:
labels

['a', 'b', 'c']

In [36]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [37]:
mix_data=[1,"cat",True]

In [38]:
pd.Series(mix_data)

0       1
1     cat
2    True
dtype: object

# sorting index, sorting values, check data if it is in the pd.Series

In [39]:
s = pd.Series(['p', 'q', 'r', 's'], index=[3, 2, 4, 5])
s.sort_index()            # index e göre sıraladı

2    q
3    p
4    r
5    s
dtype: object

In [48]:
s

3    p
2    q
4    r
5    s
dtype: object

In [40]:
s.sort_index()   


2    q
3    p
4    r
5    s
dtype: object

In [41]:
s.sort_index(ascending=False) # ascending false olursa tersten

5    s
4    r
3    p
2    q
dtype: object

In [42]:
s.sort_index(inplace=True) # kalıcı yapar
s

2    q
3    p
4    r
5    s
dtype: object

In [43]:
s = pd.Series(['p', 'q', 'r', 's'], index=[3, 2, 4, np.nan])
s.sort_index(na_position='first') # nan es sona gider, position first en baş

NaN    s
2.0    q
3.0    p
4.0    r
dtype: object

In [44]:
s.sort_index()  # nan sonda

2.0    q
3.0    p
4.0    r
NaN    s
dtype: object

In [45]:
s = pd.Series(['z', 'a', 'r', 's'], index=[3, 2, 4, np.nan])
s.sort_values()  # valulara bakar

2.0    a
4.0    r
NaN    s
3.0    z
dtype: object

In [46]:
s.sort_values(ascending=False, inplace=True)
s         #kalıcı yapar, nan sonda, valular tersten z den 

3.0    z
NaN    s
4.0    r
2.0    a
dtype: object


# "isin" ---  içindemi   indexte true false dönderir

In [48]:
s = pd.Series(['dog', 'cow', 'dog', 'cat', 'dog',
               'lion'], name='animal')

In [49]:
s.isin(['cow', 'dog'])

0     True
1     True
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

In [50]:
s.isin(['dog'])

0     True
1    False
2     True
3    False
4     True
5    False
Name: animal, dtype: bool

# index pandas series

In [51]:
ser1=pd.Series([1,2,3,4],index=["usa","germany","ussr","japan"])
ser1

usa        1
germany    2
ussr       3
japan      4
dtype: int64

In [52]:
ser2=pd.Series([1,2,5,4],index=["usa","germany","italy","japan"])

In [68]:
ser2

usa        1
germany    2
italy      5
japan      4
dtype: int64

In [53]:
ser1["usa"]  # sözlükteki gibi key ile aldık

1

In [54]:
ser1[0]    # sözlükteki gibi index ile aldık

1

In [55]:
labels

['a', 'b', 'c']

In [56]:
ser3=pd.Series(data=labels)

In [57]:
ser3

0    a
1    b
2    c
dtype: object

In [58]:
ser3[0]

'a'

In [59]:
ser1+ser2   # 2 seri değerleri topladı karşılığı yoksa boş nan gelir

germany    4.0
italy      NaN
japan      8.0
usa        2.0
ussr       NaN
dtype: float64

In [60]:
## indexing Examples

In [61]:
a=np.array([1,2,33,444,75])

In [62]:
pan_ser=pd.Series(a)
pan_ser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [63]:
pan_ser[0]

1

In [64]:
pan_ser[1:3]

1     2
2    33
dtype: int32

In [65]:
pan_ser=pd.Series([121,20,150,99], index=["ali","veli","ayşe","nur"])
pan_ser

ali     121
veli     20
ayşe    150
nur      99
dtype: int64

In [66]:
pan_ser["ali"]

121

In [67]:
pan_ser[["veli","nur"]] # fancy ile içiçe aldık farklı indexleri alırız ayrı

veli    20
nur     99
dtype: int64

In [68]:
pan_ser["veli":"nur"]  #isimde aralık aladabiliriz """"""son da"""""" dahil

veli     20
ayşe    150
nur      99
dtype: int64

In [69]:
pan_ser[0:3]  #indexte aralık aladabiliriz """"""son da"""""" dahil değilllll

ali     121
veli     20
ayşe    150
dtype: int64

# several selecting attributes

In [97]:
pan_ser.index

Index(['ali', 'veli', 'ayşe', 'nur'], dtype='object')

In [100]:
pan_ser.index

Index(['ali', 'veli', 'ayşe', 'nur'], dtype='object')

In [99]:
pan_ser.values

array([121,  20, 150,  99], dtype=int64)

In [101]:
pan_ser.items()

In [102]:
list(pan_ser.items())  # görünür hale geltiririz *, for ilede gelir

[('ali', 121), ('veli', 20), ('ayşe', 150), ('nur', 99)]

In [103]:
for index,value in pan_ser.items():
    print(index,"-",value)

ali - 121
veli - 20
ayşe - 150
nur - 99


In [104]:
"mehmet" in pan_ser   # indexlere bakar bence

False

In [105]:
121 in pan_ser

False

In [106]:
"ali" in pan_ser

True

In [107]:
121 in pan_ser.values  # valuelardan baktık

True

In [ ]:
121 in pan_ser

In [109]:
pan_ser["veli"]=571
panser

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [111]:
pan_ser[pan_ser>130]

veli    571
ayşe    150
dtype: int64

In [112]:
pan_ser>130

ali     False
veli     True
ayşe     True
nur     False
dtype: bool

In [115]:
pan_ser[[False,True,False,True]]

veli    571
nur      99
dtype: int64