In [2]:
import numpy as np

In [3]:
liste = [1,2,3,4,5,6,7,8]
a = np.array(liste)
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
type(a)  # değişkeninin tipini aldık

numpy.ndarray

In [6]:
a.dtype  # dizinin tuttuğu değerlerin tipini aldık. Hepsi aynı tip veri


dtype('int32')

In [7]:
a.shape  # tek boyutlu olduğu için bu dizi bir vektör

(8,)

In [10]:
a[-1]

8

In [8]:
a[2]=8

In [9]:
a

array([1, 2, 8, 4, 5, 6, 7, 8])

In [11]:
b = np.array([[1,2,3],[6,7,8]])

In [12]:
b.shape

(2, 3)

In [13]:
b[1,1]=0
b

array([[1, 2, 3],
       [6, 0, 8]])

In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
c.shape

(3, 3)

In [16]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
c[1,1]

5

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full((2,2), -1)

array([[-1, -1],
       [-1, -1]])

In [23]:
np.empty((3,4))

array([[1.12079879e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 4.75269212e-037, 3.56530452e-057,
        1.77701909e+160],
       [2.00459922e-076, 8.60100133e-067, 1.11645062e+165,
        7.67659979e-042]])

In [24]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.arange(5,60,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [27]:
np.linspace(0,10,3)  # default step 50

array([ 0.,  5., 10.])

In [30]:
np.random.random((3,3))

array([[0.01333497, 0.02191642, 0.47865008],
       [0.87358779, 0.58454595, 0.49378985],
       [0.62843893, 0.15919562, 0.36958412]])

In [33]:
np.random.randint(5,10, size=(4,4))

array([[9, 5, 7, 7],
       [5, 9, 6, 7],
       [6, 7, 5, 7],
       [7, 7, 5, 5]])

In [37]:
z= np.random.randint(2,15,size=(5,3))
z

array([[ 7,  8, 13],
       [14,  4, 13],
       [10,  7,  3],
       [13, 14,  7],
       [13, 14,  6]])

In [38]:
z.shape

(5, 3)

In [39]:
z=z.reshape(3,5)

In [40]:
z.shape

(3, 5)

In [43]:
z.ravel()

array([ 7,  8, 13, 14,  4, 13, 10,  7,  3, 13, 14,  7, 13, 14,  6])

In [44]:
z.max()

14

In [45]:
z.min()

3

In [46]:
z.argmax()

3

In [47]:
z.argmin()

8

## Stacking

In [49]:
a = np.array([[1,2],[3,4]])
b = np.array([[-1,3],[7,9]])

In [50]:
np.hstack((a,b))

array([[ 1,  2, -1,  3],
       [ 3,  4,  7,  9]])

In [51]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [-1,  3],
       [ 7,  9]])

In [52]:
dizi=np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
dizi

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
dizi_1=np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
dizi_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [54]:
np.concatenate([dizi,dizi_1], axis=0)  # Satır bazlı alt alta birleştirme

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [55]:
np.concatenate([dizi,dizi_1], axis=1)  # sütun bazlı yan yana birleştirme

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [56]:
array_1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [57]:
array_1.shape

(3, 4)

In [59]:
array_1[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [61]:
array_2 = array_1.copy()
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
array_2[1][1] = -6
array_2

array([[ 1,  2,  3,  4],
       [ 5, -6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# ">" ve "<" koşullarını artık yazmaya gerek yok ezberledik :D

## Matematiksel İşlemler

In [71]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,3],[7,9]])

In [72]:
x+y

array([[ 2,  5],
       [10, 13]])

In [73]:
x-y

array([[ 0, -1],
       [-4, -5]])

In [74]:
np.subtract(x,y)

array([[ 0, -1],
       [-4, -5]])

In [75]:
np.multiply(x,y)

array([[ 1,  6],
       [21, 36]])

In [76]:
x*y

array([[ 1,  6],
       [21, 36]])

In [77]:
np.dot(x,y)

array([[15, 21],
       [31, 45]])

In [78]:
x@y

array([[15, 21],
       [31, 45]])

In [79]:
x/y

array([[1.        , 0.66666667],
       [0.42857143, 0.44444444]])

In [81]:
np.divide(x,y)

array([[1.        , 0.66666667],
       [0.42857143, 0.44444444]])

In [82]:
x

array([[1, 2],
       [3, 4]])

In [83]:
x**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [85]:
x1=np.square(x)
x1

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [86]:
np.sqrt(x1)

array([[1., 2.],
       [3., 4.]])

In [87]:
np.exp(3)  # logaritmadaki e = exp, bu işlem e**3

20.085536923187668

In [88]:
np.log(100)

4.605170185988092

In [89]:
np.log10(100)

2.0

In [90]:
t = np.array([np.pi/6, np.pi/2, np.pi/3])
t

array([0.52359878, 1.57079633, 1.04719755])

In [91]:
np.sin(t)

array([0.5      , 1.       , 0.8660254])